name: Build Artifacts

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set up keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" > keystore.txt
        base64 --decode keystore.txt > bekeystore.jks
    - name: Fetch JRE for Steam deployment
      run: |
        echo $HOME
        mkdir ~/jdks
        cd ~/jdks
        wget https://github.com/Anuken/MindustryJreBuilds/releases/download/v2/jre-linux64.zip
        wget https://github.com/Anuken/MindustryJreBuilds/releases/download/v2/jre-windows64.zip
        wget https://github.com/Anuken/MindustryJreBuilds/releases/download/v2/jre-macos.zip
        wget https://github.com/Anuken/MindustryJreBuilds/releases/download/v1/packr.jar
        unzip jre-linux64.zip
        unzip jre-windows64.zip
        unzip jre-macos.zip
        ls
    - name: Create artifacts
      env:
        keystore_password: ${{ secrets.KEYSTORE_PASSWORD_SECRET }}
        keystore_alias_password: ${{ secrets.KEYSTORE_PASSWORD_SECRET }}
        keystore_alias: frog
        JDK_DIR: /home/runner/jdks/
      run: |
        git clone --depth=1 --branch=master https://github.com/Mindustry-Server-StarLegends/Mindustry.git
        cd Mindustry
        echo "BODY=$(git rev-parse HEAD)" >> $GITHUB_ENV
        sed -i 's/applicationId "io.anuke.mindustry"/applicationId "io.anuke.mindustry.be"/g' android/build.gradle
        sed -i 's/"io.anuke.mindustry"/"io.anuke.mindustry.be"/g' android/AndroidManifest.xml
        sed -i 's/Mindustry/Mindustry BE/g' android/res/values/strings.xml
        ./gradlew server:dist -Pbuildversion=${RELEASE_VERSION} -PshowCommitHash --stacktrace    
        echo "JDK directory: $JDK_DIR"
        echo $PWD
    - name: Upload server artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Mindustry/server/build/libs/server-release.jar
        tag: ${{ github.ref }}
  
